# Generated by Django 2.2 on 2020-01-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Artikel/Image'),
        ),
        migrations.CreateModel(
            name='SubArtikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Artikel')),
            ],
        ),
    ]
