# Generated by Django 2.2 on 2020-01-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200129_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='dibuat_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
