# Generated by Django 2.2 on 2020-01-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'ordering': ('nidn',), 'verbose_name_plural': 'Dosen'},
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tahun_semester_masuk',
            field=models.FloatField(blank=True, choices=[('2016', ((2016, '2016 Genap'), (2016.5, '2016 Ganjil'))), ('2017', ((2017, '2017 Genap'), (2017.5, '2017 Ganjil'))), ('2018', ((2018, '2018 Genap'), (2018.5, '2018 Ganjil'))), ('2019', ((2019, '2019 Genap'), (2019.5, '2019 Ganjil'))), ('2020', ((2020, '2020 Genap'), (2020.5, '2020 Ganjil'))), ('2021', ((2021, '2021 Genap'), (2021.5, '2021 Ganjil'))), ('2022', ((2022, '2022 Genap'), (2022.5, '2022 Ganjil'))), ('2023', ((2023, '2023 Genap'), (2023.5, '2023 Ganjil'))), ('2024', ((2024, '2024 Genap'), (2024.5, '2024 Ganjil'))), ('2025', ((2025, '2025 Genap'), (2025.5, '2025 Ganjil'))), ('2026', ((2026, '2026 Genap'), (2026.5, '2026 Ganjil'))), ('2027', ((2027, '2027 Genap'), (2027.5, '2027 Ganjil'))), ('2028', ((2028, '2028 Genap'), (2028.5, '2028 Ganjil'))), ('2029', ((2029, '2029 Genap'), (2029.5, '2029 Ganjil'))), ('2030', ((2030, '2030 Genap'), (2030.5, '2030 Ganjil'))), ('2031', ((2031, '2031 Genap'), (2031.5, '2031 Ganjil'))), ('2032', ((2032, '2032 Genap'), (2032.5, '2032 Ganjil'))), ('2033', ((2033, '2033 Genap'), (2033.5, '2033 Ganjil'))), ('2034', ((2034, '2034 Genap'), (2034.5, '2034 Ganjil'))), ('2035', ((2035, '2035 Genap'), (2035.5, '2035 Ganjil'))), ('2036', ((2036, '2036 Genap'), (2036.5, '2036 Ganjil'))), ('2037', ((2037, '2037 Genap'), (2037.5, '2037 Ganjil'))), ('2038', ((2038, '2038 Genap'), (2038.5, '2038 Ganjil'))), ('2039', ((2039, '2039 Genap'), (2039.5, '2039 Ganjil')))], null=True),
        ),
    ]
