# Generated by Django 2.2 on 2020-01-28 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraf', models.CharField(choices=[('Hadir', 'Hadir'), ('Alfa', 'Alfa'), ('Izin', 'Izin'), ('Sakit', 'Sakit')], default='Hadir', max_length=5)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Absensi mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, "Jum'at"), (6, 'Sabtu')])),
                ('jam_mulai', models.TimeField()),
                ('jam_akhir', models.TimeField()),
                ('tampil', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jadwal',
                'ordering': ('matakuliah__semester', 'hari', 'jam_mulai'),
            },
        ),
        migrations.CreateModel(
            name='Krs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_dosen', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Remedial', 'Remedial')], default='Baru', max_length=8)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'KRS',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('kode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nama', models.CharField(help_text='Nama mata kuliah dalam bahasa Indonesia', max_length=100, verbose_name='Nama matakuliah (ind)')),
                ('nama_asing', models.CharField(blank=True, help_text='Nama mata kuliah dalam bahasa Inggris', max_length=100, null=True, verbose_name='Nama matakuliah (Eng)')),
                ('sks', models.PositiveSmallIntegerField(verbose_name='SKS')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1 (Satu)'), (2, '2 (Dua)'), (3, '3 (Tiga)'), (4, '4 (Empat)'), (5, '5 (Lima)'), (6, '6 (Enam)'), (7, '7 (Tujuh)'), (8, '8 (Delapan)')])),
                ('aktif', models.BooleanField(default=True, verbose_name='status aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Matakuliah',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(default='D3', max_length=10, verbose_name='Kode Jenjang Pendidikan')),
                ('nama', models.CharField(max_length=100, verbose_name='Program Studi')),
                ('nama_jurusan', models.CharField(blank=True, default='D3 Keperawatan', max_length=100, null=True)),
                ('singkat', models.CharField(help_text='Singkatan nama program studi', max_length=3)),
                ('akreditasi', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('ketua', models.CharField(max_length=100, verbose_name='Ketua Program Studi')),
                ('tanggal_berdiri', models.DateField(default=datetime.date(2001, 9, 28))),
                ('sk_penyelengaraan', models.CharField(default='15037/D/T/K-III/2013', max_length=20)),
                ('tanggal_sk', models.DateField(default=datetime.date(2013, 7, 3))),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Program Studi',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RuangKuliah',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_ruangan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ruang Kuliah',
            },
        ),
        migrations.CreateModel(
            name='NilaiSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absensi', models.PositiveIntegerField(blank=True, null=True)),
                ('tugas', models.FloatField(blank=True, null=True)),
                ('uts', models.FloatField(blank=True, null=True)),
                ('uas', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, choices=[(4, 'A'), (3.5, 'B+'), (3, 'B'), (2.5, 'C+'), (2, 'C'), (1, 'D'), (0, 'E')], null=True)),
                ('dinilai_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('krs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.Krs')),
            ],
            options={
                'verbose_name_plural': 'Nilai',
            },
        ),
    ]
