# Generated by Django 2.2 on 2020-01-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_auto_20200129_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'ordering': ('kode',), 'verbose_name_plural': 'Matakuliah'},
        ),
    ]
